version: "1.0"
services:

  backend:
    build: 
      context: "./"
      dockerfile: "./containers/backend/dev/Dockerfile"
    container_name: "chat-backend"
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
    volumes:
      - ./backend:/backend
    working_dir: /backend

  frontend:
    build:
      context: "./"
      dockerfile: "./containers/frontend/dev/Dockerfile"
    command: sh -c "npm install && npm start -p 3030"
    container_name: "chat-frontend"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 3030:3030
    stdin_open: true
    tty: true
    volumes:
      - ./frontend:/frontend
    working_dir: /frontend
